version: '3'
services:

# The App
  app:
    build:
      args:
        user: ${APP_USER}
        uid: ${UID}
      context: ./
      dockerfile: Dockerfile
    image: ww2maps
    container_name: ww2maps-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

# Webserver
  nginx:
    image: nginx:1.17-alpine
    container_name: ww2maps-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html
      - ./dockerfiles/nginx:/etc/nginx/conf.d
    networks:
      - laravel

# MySQL Service
  db:
    image: mysql:8.0
    container_name: ww2maps-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      SERVICE_TAGS: ${DB_ENV}
      SERVICE_NAME: ${DB_CON}
    ports:
      - 3306:3306
    volumes:
      - ./dockerfiles/db:/docker-entrypoint-initdb.d
    networks:
      - laravel

#Docker Networks
networks:
  laravel:
    driver: bridge

#Volumes
volumes:
  db:
    driver: local
